obj-$(CONFIG_HI3XXX_MAILBOX) +=hi3xxx_mailbox.o
obj-$(CONFIG_HI3XXX_MAILBOX_DEBUGFS) +=hi3xxx_mailbox_debugfs.o
obj-$(CONFIG_HI3XXX_RPROC) +=hi3xxx_rproc.o
obj-$(CONFIG_HI3XXX_RPROC_DEBUGFS) +=hi3xxx_rproc_debugfs.o
obj-$(CONFIG_HI3XXX_MAILBOX) +=hi3xxx_mailbox_dev.o
