#=============================================================================
#=============================================================================


obj-y   += camera_legacy/
obj-y   += connectivity/
obj-y   += ext_modem/
obj-y   += sensor/
obj-y   += inputhub/
obj-y   += touthscreen/
obj-${CONFIG_HUAWEI_DSM} += dsm/
obj-$(CONFIG_SEATTLE)  += Seattle/
obj-$(CONFIG_LOGGER_EXTEND) += log/
obj-y   += audio/
obj-y   += nfc/
obj-y   += usb/
obj-$(CONFIG_ANTENNA_FPGA) += antenna_fpga/