obj-$(CONFIG_HI3XXX_IRQ_AFFINITY)			+= hi3xxx_irq_affinity.o
obj-$(CONFIG_HI3XXX_IRQ_AFFINITY_DEBUGFS)	+= irq_affinity_debugfs.o
obj-$(CONFIG_HI3XXX_POWER_OFF)				+= hi3xxx_poweroff.o
obj-$(CONFIG_HI3XXX_CMDLINE_PARSE)  += hi3xxx_cmdline_parse.o
obj-$(CONFIG_HI3XXX_SR)    += pm.o
obj-$(CONFIG_HI3XXX_SIM_HOTPLUG)			+= hisi_sim_hotplug.o
obj-$(CONFIG_HI3XXX_SR_DEBUG) 				+= hisi_lpregs.o
obj-y += hi3xxx_modem_etb.o
