EXTRA_CFLAGS   += -Idrivers/hisi/mntn


obj-y          += drv_mailbox_table.o
obj-y          += drv_mailbox_gut.o
obj-y          += drv_mailbox_ifc.o
obj-y          += drv_mailbox_msg.o
obj-y          += drv_mailbox_debug.o
obj-y          += drv_mailbox_port_linux.o
obj-y	       += drv_mailbox.o
obj-y          += drv_mailbox_test_linux.o

