#=============================================================================
#=============================================================================

obj-y += nfc/
obj-$(CONFIG_MAXQ616_POWER_SWITCH) += irda/
obj-$(CONFIG_HUAWEI_KSTATE) += hw_kstate/
obj-y += chipverification/
obj-y += ddrinfo/
