obj-$(CONFIG_HI6XXX_MODEM_MULTICORE)	+= multi_core.o icc/ common/
obj-$(CONFIG_HI6XXX_PLATFORM_INTERFACE) += interface/
obj-$(CONFIG_HI6XXX_PLATFORM_IPF)       += ipf/
obj-$(CONFIG_HI6XXX_PLATFORM_REMOTE_FILE)       += rfile/
obj-$(CONFIG_HI6XXX_PLATFORM_TIMER)     += timer/
obj-$(CONFIG_HI6XXX_PLATFORM_OM)        += om/
