#
#NoC Makefile
#

obj-$(CONFIG_HI6XXX_NOC) +=  hi6xxx_noc.o
obj-$(CONFIG_HI6XXX_NOC_ERR_PROBE) +=  hi6xxx_err_probe.o hi6xxx_noc_bus.o hi6xxx_noc_packet.o

obj-$(CONFIG_HI3XXX_NOC) +=  hisi_noc.o
obj-$(CONFIG_HI3XXX_NOC_ERR_PROBE) +=  hisi_err_probe.o hisi_noc_packet.o hisi_noc_transcation.o
