$(shell mkdir -p /home/fwx226231/v8r2_c50/device/hisi/customize/build_script/../../../../out/target/product/hi6210sft/obj/KERNEL_OBJ/arch/arm/boot/dts/auto-generate/hi6210sft)
include /home/fwx226231/v8r2_c50/device/hisi/customize/build_script/../../../../kernel/arch/arm/boot/dts/auto-generate/hi6210sft/hi6210sft_dtb.mk
dtbs: hi6210sft_dtb
$(shell mkdir -p /home/fwx226231/v8r2_c50/device/hisi/customize/build_script/../../../../out/target/product/hi6210sft/obj/KERNEL_OBJ/arch/arm/boot/dts/auto-generate/hi6220)
include /home/fwx226231/v8r2_c50/device/hisi/customize/build_script/../../../../kernel/arch/arm/boot/dts/auto-generate/hi6220/hi6220_dtb.mk
dtbs: hi6220_dtb
