/** ****************************************************************************

                    Huawei Technologies Sweden AB (C), 2001-2011

 ********************************************************************************
 * @file      CTTF_1x_MAC_Voice_Decode_PIF.h
 * @author    Automatically generated by DAISY
 * @version
 * @date      2013-12-25
 * @file
 * @brief
 * The interface is used to carry voice data from MAC to the decoder.
 * It's interface used between MAC and voice decoder.
 * @copyright Huawei Technologies Sweden AB
 *******************************************************************************/
#ifndef CTTF_1X_MAC_VOICE_DECODE_PIF_H
#define CTTF_1X_MAC_VOICE_DECODE_PIF_H

/*******************************************************************************
 1. Other files included
*******************************************************************************/
#include "vos.h"
#include "csdr_1x_decdata_pif.h"
#include "cttf_1x_voice_data_public_pif.h"

#ifdef __cplusplus
#if __cplusplus
    extern "C" {
#endif /* __cpluscplus */
#endif /* __cpluscplus */
#pragma pack(4)

/*******************************************************************************
 2. Macro definitions
*******************************************************************************/


/*******************************************************************************
 3. Enumerations declarations
*******************************************************************************/
/** ****************************************************************************
 * Name        : CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM_UINT16
 * Description : 
 *******************************************************************************/
enum CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM
{
    ID_CTTF_VOICE_1X_MAC_SPEECH_IND                         = 0x0000, /* _H2ASN_MsgChoice CTTF_VOICE_1X_MAC_SPEECH_IND_STRU*/ /**< @sa CTTF_VOICE_1X_MAC_SPEECH_IND_STRU */
    ID_CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM_BUTT      
};
typedef VOS_UINT16 CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM_UINT16;


/*******************************************************************************
 4. Message Header declaration
*******************************************************************************/

/*******************************************************************************
 5. Message declaration
*******************************************************************************/

/*******************************************************************************
 6. STRUCT and UNION declaration
*******************************************************************************/

/*******************************************************************************
 7. OTHER declarations
*******************************************************************************/
/** ****************************************************************************
 * Name        : CTTF_VOICE_1X_MAC_SPEECH_IND_STRU
 * Description : 1x_MAC_Rx uses this signal to deliver received speech data to
 * voice SO. Frame_quality roots from PHY.
 *******************************************************************************/
typedef struct
{
    VOS_MSG_HEADER                                                           /* _H2ASN_Skip */
    CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM_UINT16       enMsgId;         /* _H2ASN_Skip */
    VOS_UINT16                                              usOpId;
    CSDR_1X_FRAME_QUALITY_ENUM_UINT16                       enFrameQuality;
    MACITF_VOICE_RATE_TYPE_ENUM_UINT16                      enVoiceDataRate;
    VOS_UINT16                                              ausData[CTTF_1X_MAX_VOICE_DATA_BLOCK_SIZE];
    VOS_UINT16                                              ausReserve[1];
}CTTF_VOICE_1X_MAC_SPEECH_IND_STRU;


/*******************************************************************************
 8. Global  declaration
*******************************************************************************/

/*******************************************************************************
 9. Function declarations
*******************************************************************************/
/** ****************************************************************************
 * Name        : CTTF_1x_MAC_Voice_Decode_PIF_MSG_DATA
 * Description : H2ASN top level message structure definition
 *******************************************************************************/
typedef struct
{
    CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM_UINT16       enMsgId;     /* _H2ASN_MsgChoice_Export CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM_UINT16 */
    VOS_UINT8                                               aucMsgBlock[2];

    /* _H2ASN_MsgChoice_When_Comment CTTF_1X_MAC_VOICE_DECODE_PIF_MSG_TYPE_ENUM_UINT16 */
}CTTF_1x_MAC_Voice_Decode_PIF_MSG_DATA;

/* _H2ASN_Length UINT32*/
/** ****************************************************************************
 * Name        : CTTF_1x_MAC_Voice_Decode_PIF
 * Description : H2ASN top level message structure definition
 *******************************************************************************/
typedef struct
{
    VOS_MSG_HEADER
    CTTF_1x_MAC_Voice_Decode_PIF_MSG_DATA                   stMsgData;
}CTTF_1x_MAC_Voice_Decode_PIF;


#if ((VOS_OS_VER == VOS_WIN32) || (VOS_OS_VER == VOS_NUCLEUS))
#pragma pack()
#else
#pragma pack(0)
#endif

#ifdef __cplusplus
#if __cplusplus
}
#endif /* __cpluscplus */
#endif /* __cpluscplus */

#endif
