EXTRA_CFLAGS                    += -Idrivers/usb/gadget/
EXTRA_CFLAGS                    += -Idrivers/usb/susb/

obj-$(CONFIG_HISILICON_PLATFORM_USB)	+= usb_shell.o drv_if_usb.o acm_ldisc.o acm_ncopy_io.o

