# hifi dsp device driver

obj-$(CONFIG_SND_HIFI_LPP_HI3XXX)	+= hifi_lpp.o
obj-$(CONFIG_SND_HIFI_LOAD_HI3XXX)	+= hifi_loader.o
obj-$(CONFIG_SND_HIFI_SEC_LOAD_HI3XXX) += hifi_sec_loader.o
EXTRA_CFLAGS += -Idrivers/hisi/hifi_mailbox/mailbox
EXTRA_CFLAGS += -Idrivers/hisi/hifi_mailbox/ipcm


