obj-$(CONFIG_BATTERY_HI6XXX_SMARTSTAR)	+= hi6xxx_battery_data.o hi6xxx_smartstar_coul.o
obj-$(CONFIG_BATTERY_HISI_COUL)		+= hisi_coul_drv.o
obj-$(CONFIG_BQ_BCI_BATTERY)		+= bq_bci_battery.o
#obj-$(CONFIG_BQ2419X_CHARGER)		+= bq2419x_charger.o pd_charge_flag_parse.o
obj-$(CONFIG_BQ2419X_CHARGER)		+= bq2419x_charger.o
obj-$(CONFIG_HI6521_CHARGER)		+= hi6xxx_scharger_v200.o
