ifeq ($(TARGET_ARM_TYPE), arm64)
EXTRA_CFLAGS += -Iarch/arm64/include/asm
else
EXTRA_CFLAGS += -Iarch/arm/include/asm
endif
EXTRA_CFLAGS += -Iinclude/linux
EXTRA_CFLAGS += -Iinclude/generated
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/config/log/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/config/nvim/include/gu/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/config/osa/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/config/nvim/include/lt/tlps/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/config/product/define/$(OBB_PRODUCT_NAME)/config/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/config/product/define/$(OBB_PRODUCT_NAME)/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/app/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/drv/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/med/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/comm/om/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/gu/osa/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/comm/scm/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/gu/si/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/comm/socp/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/gu/usimm/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/comm/errno/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/comm/dms/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/comm/nvim/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/comm/cpm/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/gu/log/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/gu/om/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/gu/nvim/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/gu/hpa/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/lt/msp/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/oam/lt/diag/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/phy/gphy/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/phy/wphy/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/phy/lphy/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/ps/gups/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/ps/tlps/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/ps/nas/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/taf/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/tools/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/nv/gu/oam/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/nv/gu/drv/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/nv/gu/codec/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/nv/gu/gas/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/nv/gu/nas/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/nv/gu/phy/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/nv/gu/tool/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/nv/gu/ttf/
EXTRA_CFLAGS += -Idrivers/hisi/modem/include/nv/gu/was/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/comm/acore/dms/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/comm/ccore/om/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/gu/ccore/usimm/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/comm/ccore/xml/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/gu/comm/si/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/comm/comm/nvim/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/comm/comm/ppm/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/gu/acore/om/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/gu/acore/cbtcpm/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/gu/acore/cbtppm/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/gu/ccore/hpa/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/gu/ccore/nvim/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/gu/ccore/om/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/gu/ccore/pstool/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/gu/ccore/sc/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/gu/ccore/sleep/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/gu/comm/om/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/gu/comm/bbplog/


#lt only INC
ifneq ($(CFG_RAT_MODE),RAT_GU)
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/comm/acore/dms/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/comm/comm/nvim/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/gu/comm/si/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/comm/ccore/om/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/lt/comm/list/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/lt/acore/diag/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/lt/comm/drx/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/lt/comm/cfg/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/lt/comm/diag/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/lt/comm/ipc/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/lt/comm/nvim/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/lt/comm/sdm/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/lt/comm/type/
EXTRA_CFLAGS += -Idrivers/hisi/modem/oam/inc/gu/acore/om/
EXTRA_CFLAGS += -Idrivers/hisi/modem/taf/comm/src/acore/at/inc/
EXTRA_CFLAGS += -Idrivers/hisi/modem/taf/lt/inc/acore/at/
endif

EXTRA_CFLAGS +=  -DVOS_LINUX=4 -DOSA_CPU_ACPU=1 -DVOS_OS_VER=VOS_LINUX -DVOS_OSA_CPU=OSA_CPU_ACPU -D__LOG_RELEASE__ -DBSP_CORE_APP -DGU_MODE -DMSP_SUPPORT_USB_VCOM1 -DMSP_SUPPORT_USB_VCOM2 -DVOS_DOPRA_VER=2 -DNDIS_RELEASE -DBALONG_PHY_V200=2 -DBALONG_PHY_V300=3 -DBALONG_PHY_VER=BALONG_PHY_V300 -DBALONG_CHIP_V200=2 -DBALONG_CHIP_V300=3 -DBALONG_CHIP_V500=4 -DBALONG_CHIP_VER=BALONG_CHIP_V500 -DMSP_GUNAS_AT_UNITE

ifneq ($(TARGET_ARM_TYPE), arm64)
EXTRA_CFLAGS += -D__LINUX_ARM_ARCH__=7 -march=armv7-a -Uarm
endif

ifneq ($(CFG_RAT_MODE),RAT_GU)
EXTRA_CFLAGS += -DPRODUCT_CFG_MULTIMODE_LTE -DHAL_DIAG_SDM_USE
endif


ifeq ($(strip $(OBB_UE_MODE_CDMA)),true)
EXTRA_CFLAGS += -DFEATURE_UE_MODE_CDMA=FEATURE_ON
else
EXTRA_CFLAGS += -DFEATURE_UE_MODE_CDMA=FEATURE_OFF
endif

EXTRA_CFLAGS += -fsigned-char 

MSP-objs := gu/acore/pslog/pslogapp.o
MSP-objs += gu/acore/pslog/pslogadapterapp.o
MSP-objs += gu/acore/om/omappcommrx.o
MSP-objs += gu/acore/om/omapp.o
MSP-objs += gu/acore/om/omapprl.o
MSP-objs += gu/acore/om/omappoutside.o
MSP-objs += gu/acore/om/omappagent.o
MSP-objs += gu/acore/om/omprintf.o
MSP-objs += gu/acore/om/ompcvoice.o
MSP-objs += gu/acore/om/omsdlog.o
MSP-objs += gu/acore/om/omerrorlog.o
MSP-objs += gu/acore/bbplog/omappbbplog.o
MSP-objs += gu/acore/om/Omappoperator.o
MSP-objs += gu/acore/om/fastlz.o
MSP-objs += gu/acore/cbtcpm/CbtCpm.o
MSP-objs += gu/acore/cbtppm/CbtPpm.o
MSP-objs += gu/acore/cbtscm/CBTSCMSoftDecode.o
MSP-objs += gu/comm/om/OmHdlc.o
MSP-objs += gu/comm/om/omringbuffer.o
MSP-objs += gu/comm/om/ombufmngr.o
MSP-objs += gu/acore/osa/linux_sem.o
MSP-objs += gu/acore/osa/linux_task.o
MSP-objs += gu/acore/si/PcscProc.o
MSP-objs += comm/acore/cpm/cpm.o
MSP-objs += comm/acore/ppm/OmCommonPpm.o
MSP-objs += comm/acore/ppm/OmFsPpm.o
MSP-objs += comm/acore/ppm/OmHsicPpm.o
MSP-objs += comm/acore/ppm/OmSdPpm.o
MSP-objs += comm/acore/ppm/OmSocketPpm.o
MSP-objs += comm/acore/ppm/OmUsbPpm.o
MSP-objs += comm/acore/ppm/OmVcomPpm.o
MSP-objs += gu/comm/osa/v_blkmem.o
MSP-objs += gu/comm/osa/v_int.o
MSP-objs += gu/comm/osa/rtc_timer.o
MSP-objs += gu/comm/osa/v_queue.o
MSP-objs += gu/comm/osa/v_timer.o
MSP-objs += gu/comm/osa/v_msg.o
MSP-objs += gu/comm/osa/v_lib.o
MSP-objs += gu/comm/osa/vos_Id.o
MSP-objs += gu/comm/osa/vos_main.o
MSP-objs += gu/comm/osa/vos_outside.o
MSP-objs += gu/comm/osa/watchdog.o
MSP-objs += gu/comm/osa/v_nsprintf.o
MSP-objs += gu/comm/osa/v_sprintf.o
MSP-objs += gu/comm/si/pbapi.o
MSP-objs += gu/comm/si/pbmsg.o
MSP-objs += gu/comm/si/pbdata.o
MSP-objs += gu/comm/si/stkapi.o
MSP-objs += gu/comm/si/pihapi.o
MSP-objs += comm/comm/scm/SCMProc.o
MSP-objs += comm/comm/scm/SCMSoftDecode.o
MSP-objs += comm/comm/socp/BSP_SOCP.o

ifneq ($(CFG_RAT_MODE),RAT_GU)
MSP-objs += comm/comm/nvim/Nvm_fw_api.o
MSP-objs += comm/comm/nvim/Nvm_fw_proc.o
MSP-objs += lt/comm/diag/diag_api.o
MSP-objs += lt/comm/diag/diag_test.o
MSP-objs += lt/comm/diag/diag_common.o
MSP-objs += lt/comm/diag/diag_buf_ctrl.o
MSP-objs += lt/comm/diag/diag_cfg.o
MSP-objs += lt/comm/diag/diag_debug.o
MSP-objs += lt/comm/diag/diag_fs_proc.o
MSP-objs += lt/acore/diag/diag_fw.o
MSP-objs += lt/acore/diag/diag_app_agent.o
MSP-objs += lt/acore/diag/socp_lfix_chan.o
MSP-objs += lt/comm/drx/drx_msp_api.o
MSP-objs += lt/comm/drx/drx_msp_test.o
MSP-objs += lt/comm/list/blist.o

endif

obj-y  := MSP.o



